/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bulldog_linux_jni_NativeMmap */

#ifndef _Included_org_bulldog_linux_jni_NativeMmap
#define _Included_org_bulldog_linux_jni_NativeMmap
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bulldog_linux_jni_NativeMmap
 * Method:    createMap
 * Signature: (JJIIJ)J
 */
JNIEXPORT jlong JNICALL Java_org_bulldog_linux_jni_NativeMmap_createMap
  (JNIEnv *, jobject, jlong, jlong, jint, jint, jint, jlong);

/*
 * Class:     org_bulldog_linux_jni_NativeMmap
 * Method:    deleteMap
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_linux_jni_NativeMmap_deleteMap
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     org_bulldog_linux_jni_NativeMmap
 * Method:    setValueAt
 * Signature: (LI)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_linux_jni_NativeMmap_setValueAt
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeMmap
 * Method:    getValueAt
 * Signature: (L)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeMmap_getValueAt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
