/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bulldog_linux_jni_NativeSerial */

#ifndef _Included_org_bulldog_linux_jni_NativeSerial
#define _Included_org_bulldog_linux_jni_NativeSerial
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bulldog_linux_jni_NativeSerial_SERIAL_BLOCK
#define org_bulldog_linux_jni_NativeSerial_SERIAL_BLOCK 1L
#undef org_bulldog_linux_jni_NativeSerial_SERIAL_NO_BLOCK
#define org_bulldog_linux_jni_NativeSerial_SERIAL_NO_BLOCK 0L
#undef org_bulldog_linux_jni_NativeSerial_SERIAL_DEFAULT_TIMEOUT
#define org_bulldog_linux_jni_NativeSerial_SERIAL_DEFAULT_TIMEOUT 5L
#undef org_bulldog_linux_jni_NativeSerial_PARENB
#define org_bulldog_linux_jni_NativeSerial_PARENB 1024i64
#undef org_bulldog_linux_jni_NativeSerial_PARODD
#define org_bulldog_linux_jni_NativeSerial_PARODD 4096i64
#undef org_bulldog_linux_jni_NativeSerial_CMSPAR
#define org_bulldog_linux_jni_NativeSerial_CMSPAR 1099511627776i64
/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialOpen
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialOpen__Ljava_lang_String_2I
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialOpen
 * Signature: (Ljava/lang/String;IIZIII)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialOpen__Ljava_lang_String_2IIZIII
  (JNIEnv *, jclass, jstring, jint, jint, jboolean, jint, jint, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialRead
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialReadBuffer
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialReadBuffer
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialDataAvailable
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialDataAvailable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialWrite
 * Signature: (IB)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialWrite
  (JNIEnv *, jclass, jint, jbyte);

/*
 * Class:     org_bulldog_linux_jni_NativeSerial
 * Method:    serialWriteBuffer
 * Signature: (ILjava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_linux_jni_NativeSerial_serialWriteBuffer
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
