/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bulldog_beagleboneblack_jni_NativeAdc */

#ifndef _Included_org_bulldog_beagleboneblack_jni_NativeAdc
#define _Included_org_bulldog_beagleboneblack_jni_NativeAdc
#ifdef __cplusplus
extern "C" {
#endif
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_ONE_SHOOT
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_ONE_SHOOT 0L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_CONTINUOUS
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_SW_CONTINUOUS 1L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_ONE_SHOOT
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_ONE_SHOOT 2L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_CONTINUOUS
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_MODE_HW_CONTINUOUS 3L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_1
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_1 0L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_2
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_2 1L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_4
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_4 2L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_8
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_8 3L
#undef org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_16
#define org_bulldog_beagleboneblack_jni_NativeAdc_BBBIO_ADC_STEP_AVG_16 4L
/*
 * Class:     org_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_beagleboneblack_jni_NativeAdc_setup
  (JNIEnv *, jclass);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    teardown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativeAdc_teardown
  (JNIEnv *, jclass);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    fetchSamples
 * Signature: (I)[F
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativeAdc_fetchSamples
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    configureModule
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativeAdc_configureModule
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    configureChannel
 * Signature: (IIIIILjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativeAdc_configureChannel
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jobject, jint);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    enableChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativeAdc_enableChannel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativeAdc
 * Method:    disableChannel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativeAdc_disableChannel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
