/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_bulldog_beagleboneblack_jni_NativePwm */

#ifndef _Included_org_bulldog_beagleboneblack_jni_NativePwm
#define _Included_org_bulldog_beagleboneblack_jni_NativePwm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_bulldog_beagleboneblack_jni_NativePwm
 * Method:    setup
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_beagleboneblack_jni_NativePwm_setup
  (JNIEnv *, jclass);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativePwm
 * Method:    teardown
 * Signature: ()I
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativePwm_teardown
  (JNIEnv *, jclass);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativePwm
 * Method:    setPwm
 * Signature: (IFFF)I
 */
JNIEXPORT jint JNICALL Java_org_bulldog_beagleboneblack_jni_NativePwm_setPwm
  (JNIEnv *, jclass, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativePwm
 * Method:    enable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativePwm_enable
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_bulldog_beagleboneblack_jni_NativePwm
 * Method:    disable
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_bulldog_beagleboneblack_jni_NativePwm_disable
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
